version: '3.5'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: renlife_demo
    ports:
      - "5432:5432"
