server:
  port: 8089
  error:
    include-message: always
  shutdown: graceful

logging:
  level:
    reactor:
      netty:
        http:
          client: INFO
    org:
      springframework: INFO
    root: INFO

spring:
  main:
    banner-mode: "off"
  application:
    name: renlife_demo
  mvc:
    log-request-details: true
  jmx:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/renlife_demo
    username: docker
    password: docker
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        types:
          print:
            banner: false
  sql:
    init:
      platform: postgres